### ISSUE TITLE
httpOnly: false is it safe? use an api to get cookie server side instead?

### ISSUE THREAD

**Issue by robthepaper** [jianyuan/pocketbase-sveltekit-auth#172]
Hi @jianyuan ,
thanks for your project, I am using part of your code to implement with my project.
Was wondering if it is safe to set httpOnly to false?

What do you think about setting an server side api to retrieve the cookie content instead of accessing it in js client side with document.cookie?

**Comment by kylejsarte** [comment]
@robthepaper Standard security practice would suggest to set `httpOnly` to true so the cookie [cannot be accessed through client side script](https://owasp.org/www-community/HttpOnly). This would be in addition to other settings like `secure` and `sameSite` i.e.:

```
response.headers.set('set-cookie', event.locals.pb.authStore.exportToCookie({ 
    secure: true,      
    httpOnly: true,
    sameSite: 'Strict'
}));
```

I'm not personally using this project template, but from a brief look I configure my hooks.server.ts similarly. Specifically, once you have the user model stored in `locals` i.e.:

```
  event.locals.user = pb.authStore.model
```

You can use it throughout your application (both server and client side) for protecting routes or conditional markup.

**Comment by jianyuan** [comment]
If you only want to handle things on the server side, you can set `httpOnly` to `true`. This means you cannot use the PocketBase JS SDK on the client, missing out on features like direct file uploads, subscriptions to real-time changes, and authentication handling (e.g., redirecting to an OAuth2 provider). You will need to implement a proxy on the backend.
