### ISSUE TITLE
Logged-in user data not available during SSR

### ISSUE THREAD

**Issue by zakkor** [jianyuan/pocketbase-sveltekit-auth#3]
The logged in user's session does not get sent from the server render, causing a "flash of logged-out content".

When the client scripts kick in, the user is correctly shown as being logged in.

Here's a video showing what I mean: https://gfycat.com/tintedunrulygemsbok

**Comment by jianyuan** [comment]
@zakkor You can use server-side rendering to avoid this. Something like this works: https://github.com/jianyuan/pocketbase-sveltekit-auth/pull/4
