### ISSUE TITLE
`hooks.server.ts` should use a new PocketBase instance for each request

### ISSUE THREAD

**Issue by ganigeorgiev** [jianyuan/pocketbase-sveltekit-auth#62]
This template was shared with me in https://github.com/pocketbase/pocketbase/discussions/2949, but I noticed that it loads a single global PocketBase instance for each request in `hooks.server.ts`.

As mentioned in the above discussion, unless I'm misunderstanding the structure of the application, `event.locals.pb = pb` doesn't create a new instance. It uses the same object instantiated in `$lib/pocketbase.ts`.

You need to create a new PocketBase instance for each server-side request because requests from different users could write over the same `pb.authStore` object.

For `hooks.client.ts` is OK to have a single global PocketBase instance because the `pb.authStore` in this case is kept in the user's browser and it is not shared with the other users.

My recommendation would be to create and export a **function** from `$lib/pocketbase.ts` that will create a new PocketBase instance every time when it is called in `hooks.server.ts`.

**Comment by jianyuan** [comment]
Thanks for reporting, @ganigeorgiev! I have fixed this in https://github.com/jianyuan/pocketbase-sveltekit-auth/pull/63.
