### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by pdenapo** [jianyuan/pocketbase-sveltekit-auth#66]
Under which license is this repository available? Please add a license file to let the users know.

https://docs.github.com/es/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

https://docs.github.com/es/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by jianyuan** [comment]
Done!
